import type { Json, SutContract, TestPlan, TestPlanCase } from "../../contracts.js";
import { renderNewFilePatch, type RenderedPatch } from "./patch.js";

export interface GoTestRenderOptions {
  readonly outputPath?: string;
  readonly packageName?: string;
}

export function renderGoCommandTests(
  plan: TestPlan,
  contract: SutContract,
  options: GoTestRenderOptions = {},
): RenderedPatch {
  const operationById = new Map(contract.operations.map((operation) => [operation.id, operation]));
  const tests = plan.cases.flatMap((testCase) => {
    const step = testCase.steps[0];
    if (step === undefined) return [];
    const operation = operationById.get(step.operationId);
    if (
      operation?.interactionKind !== "command" ||
      operation.extensionSchema !== "hypertest.command-operation/v1" ||
      !isRecord(operation.extension)
    ) return [];
    return [renderCase(testCase, operation.extension)];
  });

  const content = `// Code generated by HyperTest. DO NOT EDIT.\n` +
    `package ${options.packageName ?? "hyperfixture_test"}\n\n` +
    `import (\n` +
    `\t\"bytes\"\n` +
    `\t\"os/exec\"\n` +
    `\t\"testing\"\n` +
    `)\n\n` +
    tests.join("\n\n") +
    "\n";
  return renderNewFilePatch(options.outputPath ?? "hypertest_generated_test.go", content);
}

function renderCase(testCase: TestPlanCase, extension: Record<string, Json>): string {
  const step = testCase.steps[0]!;
  const template = Array.isArray(extension.argv)
    ? extension.argv.filter((item): item is string => typeof item === "string")
    : [];
  const argv = template.map((part) => substitute(part, step.input));
  const command = argv[0] ?? "false";
  const args = argv.slice(1);
  const input = isRecord(step.input) ? step.input : {};
  const stdin = typeof input.stdin === "string" ? input.stdin : "";
  const expectedValidity = readExpectedValidity(testCase);
  const check = expectedValidity === "invalid"
    ? [
        `\tif err == nil {`,
        `\t\tt.Fatalf(\"expected command rejection, got success: %s\", stdout.String())`,
        `\t}`,
      ]
    : [
        `\tif err != nil {`,
        `\t\tt.Fatalf(\"command failed: %v; stdout=%s stderr=%s\", err, stdout.String(), stderr.String())`,
        `\t}`,
      ];
  return [
    `func Test${goIdentifier(testCase.id)}(t *testing.T) {`,
    `\tcmd := exec.Command(${[goString(command), ...args.map(goString)].join(", ")})`,
    `\tcmd.Stdin = bytes.NewBufferString(${goString(stdin)})`,
    `\tvar stdout, stderr bytes.Buffer`,
    `\tcmd.Stdout = &stdout`,
    `\tcmd.Stderr = &stderr`,
    `\terr := cmd.Run()`,
    ...check,
    `}`,
  ].join("\n");
}

function substitute(template: string, input: Json): string {
  return template.replace(/\{([^}]+)\}/g, (_match, path: string) => {
    const value = lookup(input, path);
    if (value === undefined || value === null) return "";
    if (typeof value === "string") return value;
    return JSON.stringify(value);
  });
}

function lookup(value: Json, path: string): Json | undefined {
  let current: Json | undefined = value;
  for (const segment of path.split(".")) {
    if (!isRecord(current)) return undefined;
    current = current[segment];
  }
  return current;
}

function readExpectedValidity(testCase: TestPlanCase): string {
  for (const oracle of testCase.oracles) {
    if (isRecord(oracle.expression) && typeof oracle.expression.expectedValidity === "string") {
      return oracle.expression.expectedValidity;
    }
  }
  return "unknown";
}

function goIdentifier(value: string): string {
  const parts = value.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const identifier = parts.map((part) => part[0]?.toUpperCase() + part.slice(1)).join("");
  return /^\d/.test(identifier) ? `Case${identifier}` : identifier || "Case";
}

function goString(value: string): string {
  return JSON.stringify(value);
}

function isRecord(value: Json | undefined): value is Record<string, Json> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export interface GoTestRunMetadata {
  readonly runId: string;
  readonly sourceRevision: string;
  readonly command: readonly string[];
  readonly exitCode: number;
  readonly startedAtEpochMs: number;
  readonly finishedAtEpochMs: number;
  readonly stderr?: string;
}

interface GoTestEvent {
  readonly Time?: string;
  readonly Action?: string;
  readonly Package?: string;
  readonly Test?: string;
  readonly Elapsed?: number;
  readonly Output?: string;
}

export function parseGoTestJson(
  text: string,
  metadata: GoTestRunMetadata,
): import("../../contracts.js").TestRun {
  const events: GoTestEvent[] = [];
  const unparsed: string[] = [];
  for (const line of text.split(/\r?\n/)) {
    if (line.trim().length === 0) continue;
    try {
      events.push(JSON.parse(line) as GoTestEvent);
    } catch {
      unparsed.push(line);
    }
  }
  const caseMap = new Map<string, import("../../contracts.js").TestCaseResult>();
  for (const event of events) {
    if (event.Test === undefined || event.Action === undefined) continue;
    if (!["pass", "fail", "skip"].includes(event.Action)) continue;
    const id = `${event.Package ?? "package"}::${event.Test}`;
    const output = events
      .filter((item) => item.Package === event.Package && item.Test === event.Test && item.Output !== undefined)
      .map((item) => item.Output)
      .join("");
    caseMap.set(id, {
      id,
      name: event.Test,
      status: event.Action === "pass" ? "passed" : event.Action === "skip" ? "skipped" : "failed",
      ...(event.Elapsed === undefined ? {} : { durationMs: event.Elapsed * 1_000 }),
      ...(output.length === 0 ? {} : { stdout: output }),
      evidence: [],
      metadata: { package: event.Package ?? "" },
    });
  }
  const packageFailureWithoutTest = events.some(
    (event) => event.Action === "fail" && event.Test === undefined,
  );
  const buildLikeOutput = events
    .filter((event) => event.Test === undefined)
    .map((event) => event.Output ?? "")
    .join("");
  const cases = [...caseMap.values()];
  const status = metadata.exitCode === 0
    ? "passed"
    : cases.some((item) => item.status === "failed")
      ? "failed"
      : packageFailureWithoutTest && /(?:build failed|undefined:|cannot use|syntax error)/i.test(buildLikeOutput)
        ? "build_error"
        : "runner_error";
  return {
    schema: "hypertest.test-run/v1",
    runId: metadata.runId,
    sourceRevision: metadata.sourceRevision,
    status,
    command: metadata.command,
    exitCode: metadata.exitCode,
    startedAtEpochMs: metadata.startedAtEpochMs,
    finishedAtEpochMs: metadata.finishedAtEpochMs,
    cases,
    stdout: text,
    ...(metadata.stderr === undefined ? {} : { stderr: metadata.stderr }),
    rawArtifacts: [],
    coverageArtifacts: [],
    ...(unparsed.length === 0 ? {} : { metadata: { unparsedLines: unparsed } }),
  };
}
