import type { Json, SutContract, TestPlan, TestPlanCase } from "../../contracts.js";
import { renderNewFilePatch, type RenderedPatch } from "./patch.js";

export interface PytestRenderOptions {
  readonly outputPath?: string;
  readonly baseUrlEnvironmentVariable?: string;
}

export function renderPytestHttp(
  plan: TestPlan,
  contract: SutContract,
  options: PytestRenderOptions = {},
): RenderedPatch {
  const operationById = new Map(contract.operations.map((operation) => [operation.id, operation]));
  const tests = plan.cases.flatMap((testCase) => {
    const step = testCase.steps[0];
    if (step === undefined) return [];
    const operation = operationById.get(step.operationId);
    if (
      operation?.interactionKind !== "http" ||
      operation.extensionSchema !== "hypertest.http-operation/v1" ||
      !isRecord(operation.extension)
    ) {
      return [];
    }
    return [renderCase(testCase, operation.extension)];
  });

  const environment = options.baseUrlEnvironmentVariable ?? "HYPERTEST_BASE_URL";
  const content = `# Generated by HyperTest. Edit the framework adapter, not this file.\n` +
    `import json\n` +
    `import os\n` +
    `import urllib.error\n` +
    `import urllib.parse\n` +
    `import urllib.request\n\n` +
    `BASE_URL = os.environ.get(${pythonString(environment)}, "http://127.0.0.1:8765").rstrip("/")\n\n` +
    `def _invoke(method, path, payload):\n` +
    `    path_values = {}\n` +
    `    query = {}\n` +
    `    headers = {}\n` +
    `    body = None\n` +
    `    if isinstance(payload, dict):\n` +
    `        for key, value in payload.items():\n` +
    `            if key.startswith("path."):\n` +
    `                path_values[key[5:]] = value\n` +
    `            elif key.startswith("query."):\n` +
    `                query[key[6:]] = value\n` +
    `            elif key.startswith("header."):\n` +
    `                headers[key[7:]] = str(value)\n` +
    `            elif key == "body":\n` +
    `                body = value\n` +
    `    for name, value in path_values.items():\n` +
    `        path = path.replace("{" + name + "}", urllib.parse.quote(str(value), safe=""))\n` +
    `    url = BASE_URL + path\n` +
    `    if query:\n` +
    `        url += "?" + urllib.parse.urlencode(query, doseq=True)\n` +
    `    data = None if body is None else json.dumps(body).encode("utf-8")\n` +
    `    if data is not None:\n` +
    `        headers.setdefault("Content-Type", "application/json")\n` +
    `    request = urllib.request.Request(url, data=data, headers=headers, method=method)\n` +
    `    try:\n` +
    `        with urllib.request.urlopen(request, timeout=5) as response:\n` +
    `            return response.status, response.read().decode("utf-8")\n` +
    `    except urllib.error.HTTPError as error:\n` +
    `        return error.code, error.read().decode("utf-8")\n\n` +
    tests.join("\n\n") +
    "\n";

  return renderNewFilePatch(options.outputPath ?? "tests/generated/test_hypertest_generated.py", content);
}

function renderCase(testCase: TestPlanCase, extension: Record<string, Json>): string {
  const step = testCase.steps[0]!;
  const method = typeof extension.method === "string" ? extension.method : "GET";
  const path = typeof extension.path === "string" ? extension.path : "/";
  const expectedStatuses = Array.isArray(extension.expectedStatuses)
    ? extension.expectedStatuses.filter((item): item is string => typeof item === "string" && /^\d{3}$/.test(item)).map(Number)
    : [];
  const expectedValidity = readExpectedValidity(testCase);
  const assertion =
    expectedValidity === "invalid"
      ? "assert 400 <= status < 500, f\"expected safe client rejection, got {status}: {body}\""
      : expectedStatuses.length > 0
        ? `assert status in ${pythonValue(expectedStatuses)}, f\"unexpected status {status}: {body}\"`
        : "assert status < 500, f\"unexpected server failure {status}: {body}\"";
  return [
    `def test_${sanitize(testCase.id)}():`,
    `    \"\"\"${escapeDoc(testCase.objective)}\"\"\"`,
    `    status, body = _invoke(${pythonString(method)}, ${pythonString(path)}, ${pythonValue(step.input)})`,
    `    ${assertion}`,
  ].join("\n");
}

function readExpectedValidity(testCase: TestPlanCase): string {
  for (const oracle of testCase.oracles) {
    if (isRecord(oracle.expression) && typeof oracle.expression.expectedValidity === "string") {
      return oracle.expression.expectedValidity;
    }
  }
  return "unknown";
}

function pythonValue(value: Json | readonly number[]): string {
  if (value === null) return "None";
  if (value === true) return "True";
  if (value === false) return "False";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "None";
  if (typeof value === "string") return pythonString(value);
  if (Array.isArray(value)) return `[${value.map((item) => pythonValue(item as Json)).join(", ")}]`;
  return `{${Object.entries(value).map(([key, item]) => `${pythonString(key)}: ${pythonValue(item)}`).join(", ")}}`;
}

function pythonString(value: string): string {
  return JSON.stringify(value).replaceAll("\\u2028", "\\u2028").replaceAll("\\u2029", "\\u2029");
}

function sanitize(value: string): string {
  const normalized = value.toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_+|_+$/g, "");
  return normalized.length === 0 ? "case" : normalized;
}

function escapeDoc(value: string): string {
  return value.replaceAll('"""', "\\\"\\\"\\\"").replaceAll("\n", " ");
}

function isRecord(value: Json | undefined): value is Record<string, Json> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export interface PytestRunMetadata {
  readonly runId: string;
  readonly sourceRevision: string;
  readonly command: readonly string[];
  readonly exitCode: number;
  readonly startedAtEpochMs: number;
  readonly finishedAtEpochMs: number;
  readonly stdout?: string;
  readonly stderr?: string;
}

export function parsePytestJunit(
  xml: string,
  metadata: PytestRunMetadata,
): import("../../contracts.js").TestRun {
  const cases: import("../../contracts.js").TestCaseResult[] = [];
  const pattern = /<testcase\b([^>]*?)(?:\/>|>([\s\S]*?)<\/testcase>)/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(xml)) !== null) {
    const attributes = parseXmlAttributes(match[1] ?? "");
    const body = match[2] ?? "";
    const failure = /<(failure|error)\b([^>]*)>([\s\S]*?)<\/\1>/.exec(body);
    const skipped = /<skipped\b/.test(body);
    const status = skipped ? "skipped" : failure?.[1] === "error" ? "error" : failure ? "failed" : "passed";
    cases.push({
      id: `${attributes.classname ?? "case"}::${attributes.name ?? cases.length + 1}`,
      name: attributes.name ?? `case-${cases.length + 1}`,
      status,
      ...(attributes.time === undefined ? {} : { durationMs: Number(attributes.time) * 1_000 }),
      ...(failure === null ? {} : { message: decodeXml(failure[3] ?? failure[2] ?? "failure") }),
      evidence: [],
    });
  }
  const status = metadata.exitCode === 0
    ? "passed"
    : cases.some((item) => item.status === "failed" || item.status === "error")
      ? "failed"
      : metadata.exitCode === 5
        ? "runner_error"
        : "runner_error";
  return {
    schema: "hypertest.test-run/v1",
    runId: metadata.runId,
    sourceRevision: metadata.sourceRevision,
    status,
    command: metadata.command,
    exitCode: metadata.exitCode,
    startedAtEpochMs: metadata.startedAtEpochMs,
    finishedAtEpochMs: metadata.finishedAtEpochMs,
    cases,
    ...(metadata.stdout === undefined ? {} : { stdout: metadata.stdout }),
    ...(metadata.stderr === undefined ? {} : { stderr: metadata.stderr }),
    rawArtifacts: [],
    coverageArtifacts: [],
  };
}

function parseXmlAttributes(text: string): Record<string, string> {
  const output: Record<string, string> = {};
  const pattern = /([A-Za-z_:][A-Za-z0-9_.:-]*)="([^"]*)"/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(text)) !== null) {
    output[match[1] ?? ""] = decodeXml(match[2] ?? "");
  }
  return output;
}

function decodeXml(value: string): string {
  return value
    .replaceAll("&quot;", '"')
    .replaceAll("&apos;", "'")
    .replaceAll("&lt;", "<")
    .replaceAll("&gt;", ">")
    .replaceAll("&amp;", "&");
}
