/**
 * The commented `hypertest.config.yaml` written by `hypertest init`. It loads and validates as is
 * (`loadConfig`), names secrets only through `*Env` fields, and routes every core role and the GUI role once the two API keys
 * it names are set (`hypertest doctor`).
 */

/** Environment variables the template's active providers read their API keys from. */
export const TEMPLATE_KEY_VARIABLES: readonly string[] = Object.freeze(['DEEPSEEK_API_KEY', 'ANTHROPIC_API_KEY']);

/** Lines appended to .gitignore: the data directory holds the database, evidence and the private signing keys. */
export const GITIGNORE_ENTRIES: readonly string[] = Object.freeze(['.hypertest/']);

export function configTemplate(projectName: string): string {
  // JSON strings are valid YAML double-quoted scalars
  const name = JSON.stringify(projectName);
  return `# Hypertest configuration (generated by \`hypertest init\`).
#
# Secrets never live in this file. Fields ending in \`Env\` (apiKeyEnv, urlEnv, capabilitySecretEnv, ...) NAME an
# environment variable that is read when Hypertest starts; inline keys, tokens and credential headers are rejected.
# \`\${VAR}\` / \`\${VAR:-default}\` interpolation works for non-secret string values only.
#
# Check this setup with:   hypertest doctor
# Start a run with:        hypertest run "Is this change releasable?" --repo . --commit HEAD
version: 1

project:
  name: ${name}
  dataDir: .hypertest             # database, evidence artifacts, signing keys (relative to this file; keep it out of git)

# Embedded PostgreSQL (PGlite) under <dataDir>/db: one Hypertest process per data directory.
# For several processes or Temporal workers use PostgreSQL (the URL comes from the environment):
#   store: { kind: postgres, urlEnv: HYPERTEST_PG_URL, schema: hypertest }
store:
  kind: pglite

# In-process event bus; for several processes use NATS JetStream:
#   bus: { kind: nats, servers: "nats://127.0.0.1:4222" }
bus:
  kind: inprocess

# Runs are driven in this process and resumed with \`hypertest resume\` after a crash. For Temporal:
#   durable: { kind: temporal, address: "127.0.0.1:7233", workerMode: external }   # + \`hypertest worker\`
durable:
  kind: local
  maxConcurrentTurns: 4

artifacts:
  kind: fs                        # content-addressed evidence artifacts under <dataDir>/artifacts

models:
  providers:
    # DeepSeek through its OpenAI-compatible API.
    - id: deepseek
      kind: openai-compatible
      baseUrl: https://api.deepseek.com/v1
      apiKeyEnv: DEEPSEEK_API_KEY  # the variable's NAME; export DEEPSEEK_API_KEY=... in your shell or CI secret store
      timeoutMs: 180000

    # Anthropic Messages API.
    - id: anthropic
      kind: anthropic
      apiKeyEnv: ANTHROPIC_API_KEY

    # A local model behind an OpenAI-compatible endpoint (Ollama, vLLM, llama.cpp server, LM Studio, ...).
    # Uncomment it together with its route below; a local server needs no key.
    # - id: local
    #   kind: openai-compatible
    #   baseUrl: "\${LOCAL_LLM_URL:-http://127.0.0.1:11434/v1}"

  # A route is provider + model + what it can do. The router filters routes in the order
  # security → capability → role suitability → quality → latency → cost (never cost first) and falls back
  # fail-closed. \`quality\` scores are 0..1 per role or task type (\`default\` otherwise); keep them honest (evals).
  # Omitted fields take defaults (capabilities [tool_use, structured_output], contextWindow 128000, ...).
  routes:
    - routeId: deepseek-chat
      provider: deepseek
      model: deepseek-chat
      capabilities: [tool_use, parallel_tool_calls, structured_output, reasoning, long_context]
      contextWindow: 128000
      maxOutputTokens: 8192
      quality: { default: 0.8 }
      # costPerMillionInputUsd / costPerMillionOutputUsd: set them from your price list (budget accounting).

    - routeId: claude-opus
      provider: anthropic
      model: claude-opus-5
      capabilities: [tool_use, parallel_tool_calls, structured_output, reasoning, long_context, vision]
      reasoning: opaque              # thinking blocks are replayed only to the same model
      contextWindow: 1000000
      maxOutputTokens: 32000
      quality: { default: 0.9 }
      costPerMillionInputUsd: 5
      costPerMillionOutputUsd: 25
      extra: { temperature: null }   # current Claude models reject sampling parameters: drop the role policies' temperature

    - routeId: claude-sonnet
      provider: anthropic
      model: claude-sonnet-5
      capabilities: [tool_use, parallel_tool_calls, structured_output, reasoning, long_context, vision]
      reasoning: opaque
      contextWindow: 1000000
      maxOutputTokens: 32000
      quality: { default: 0.85 }
      costPerMillionInputUsd: 2
      costPerMillionOutputUsd: 10
      extra: { temperature: null }

    # - routeId: local-coder
    #   provider: local
    #   model: qwen2.5-coder:32b
    #   capabilities: [tool_use, structured_output]
    #   structuredOutput: prompted
    #   contextWindow: 32768
    #   maxDataClassification: restricted   # data never leaves the machine
    #   quality: { default: 0.6 }

    # The local_private role (restricted data: secrets, personal data) is routed ONLY to routes accepting restricted data
    # like this one; without one its work fails closed (\`hypertest doctor\` warns). vision_gui needs a vision route.

# Per-role model policies, deep-merged over the built-in role catalog. Roles: lead, code_change_analyst,
# architecture_analyst, historical_bug_analyst, test_designer, executor, rca, fixer, reviewer, metrics_analyst,
# environment, condenser, vision_gui (browser + screenshots), local_private (restricted data, local routes only). A policy may set preferredRoutes, requiredCapabilities, minQuality, allowedProviders,
# prohibitedProviders, privacyClass, independentFromRoles, maxCostPerCallUsd, latencyBudgetMs, reasoningEffort,
# temperature and fallback (revalidated | fail_closed).
roles:
  lead:                              # plans, replans and hands over to the QualityGate
    defaultModelPolicy:
      preferredRoutes: [claude-opus, deepseek-chat]
      minQuality: 0.8
  test_designer:
    defaultModelPolicy:
      preferredRoutes: [deepseek-chat, claude-sonnet]
  executor:                          # runs tests and records evidence
    defaultModelPolicy:
      preferredRoutes: [deepseek-chat]
  rca:
    defaultModelPolicy:
      preferredRoutes: [deepseek-chat, claude-sonnet]
  reviewer:                          # independent judge: a different provider than the roles it reviews
    defaultModelPolicy:
      preferredRoutes: [claude-sonnet, claude-opus]
      # every role that produces evidence, findings, tests or fixes (a list here REPLACES the built-in default: keep it
      # complete, or leave it out to inherit the catalog's list)
      independentFromRoles: [executor, test_designer, rca, fixer, metrics_analyst, environment, vision_gui, local_private]
      fallback: fail_closed
  condenser:                         # context summaries; a local route keeps them on the machine
    defaultModelPolicy:
      preferredRoutes: [deepseek-chat]

# Run limits (defaults shown in comments) and the release gate.
budget:
  maxWallClockMs: 3600000          # 1 h (default 4 h)
  maxModelTokens: 2000000          # default 5,000,000
  maxToolCalls: 1000               # default 2,000
  # maxModelCostUsd: 20
  # maxWorkItems: 200
gate:
  requireIndependentReview: true   # without an independent approval the best verdict is \`conditional\`
  failOnUnresolvedSeverity: P1     # unresolved P0/P1 findings fail the gate
  # minCoverage: { lines: 80 }
  # requireOracle: false           # only to accept a verdict with NO oracle in force (default true: such a run is inconclusive)

# Oracles: what \`correct\` means, decided by a named human, never by an agent. A run that names no oracles pins the
# ones configured here; without an approved oracle in force the best verdict is \`inconclusive\` (gate criterion C0).
# An oracle is established once (here or with \`hypertest oracle establish <file> --by <name>\`); later edits of this
# section never change it: changes go through governed proposals (\`hypertest oracle proposals\` / \`decide\`).
# oracles:
#   - oracleId: checkout-contract
#     establishedBy: alice             # the human authority recorded as the approver
#     scope: { components: [checkout], description: checkout accepts valid orders and rejects invalid ones }
#     assertions:
#       - assertionId: suite-passes
#         description: every checkout test passes
#         kind: requirement            # deterministic_invariant | requirement | differential | metamorphic | statistical | llm_semantic
#         severity: P1                 # P0/P1 assertions are critical; at least one must be deterministic
#         check: { type: test_outcome, testSelector: "*checkout*", expected: pass }

# BUGate checkout providing the protocol binding (the embedded protocol is used when absent).
# bugate:
#   path: ../BUGate

# Sandbox for commands agents run: local processes with a scrubbed environment in Linux namespaces (\`hypertest doctor\`
# checks the host supports them): no network but their own loopback and the registered environments' / allowlisted
# endpoints on this host (the SUT); keys, the store and other workspaces hidden. \`network: open\` lets commands reach
# any host (no egress governance); agents otherwise reach networks only through the governed black-box tools.
sandbox:
  kind: local
  network: loopback

tools:
  httpAllowlist: []                # black-box targets agents may call (e.g. "http://127.0.0.1:8080")
  enableBrowser: false

observability:
  logLevel: info
`;
}
